### ISSUE TITLE
Render var not working as expected

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#103]
Works: 

```yaml
envs_>:
  dev:
    num_servers: 1 # etc...
  prod:
    num_servers: 2

load environment_>: var {{envs[select(choices=keys(envs))]}} --merge
```

Doesn't:

```yaml
envs_>:
  dev:
    num_servers: 1 # etc...
  prod:
    num_servers: 2

load environment_>: {{envs[select(choices=keys(envs))]}} --merge
```

Is this the macro or parser?
