### ISSUE TITLE
Update random_string hook 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#18]
Interface is old and should probably be updated in a forward compatible way throwing a warning when expiring parameters are invoked. 

Could be more like:

```yaml
a:
  ->: random_string 4
  case: upper 
b:
  ->: random_string 4
  case: mixed
c:
  ->: random_string 4
  case: 
    - mixed
    - no_int

d: # Maybe from regex?
  ->: random_string 4
  regex: 
    - [0-9]
    - [a-zA-Z]
```
