### ISSUE TITLE
Merge overwrites with output_dict  

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#3]
It might be more natural to pre-insert these into output and then overwrite the overwrite value with the actual prompt.  Something to consider as it make sense when you have a bunch of qualifying hooks to get to a variable that you actually want to prompt for.  Little easier to have in the output_dict that value so you can skip some of the qualifying hooks. 

For example: 
```yaml
aws_instance_family_:
  type: select
  message: What instance family do you want to run?
  choices:
    - i3
    - i3en
    - c5d

aws_available_instances_:
  type: aws_ec2_types
  region: "{{ region }}"
  instance_families: ["{{ aws_instance_family_ }}"]

instance_type:
  type: select
  message: What type of data instances do you want to create?
  choices: "{{ aws_available_instances_ }}"
```

In the override file, you might just want to have `instance_type` then put the logic before the variable in a block and qualify it if `instance_type is defined` in a `when` condition.
