### ISSUE TITLE
http_put/post hooks to turn data into json by default 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#38]
To get it to work now, have to `jsonify` which is not ideal:
```
put:
  ->: http_put "https://localhost:9200/_ingest/pipeline/{{name}}"
  data: "{{data|jsonify}}"
  kwargs:
    verify: false
    headers:
      Authorization: ApiKey {{elasticsearch_api_key}}
      Content-Type: application/json
```

Don't know if this should be done by default.
