### ISSUE TITLE
Prompt outputs should be parsed for select / checkbox 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#39]
Per title, just like with match hook, the output should be parsed for hooks. For instance: 

```yaml
selection:
  ->: select
  message: What you do?
  choices:
    - I do stuff: stuff
    - I do things:
        stuff: things
        foo->: literal bar
```
