### ISSUE TITLE
Using "namespace" makes tackle go nuts 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#52]
This: 

```yaml
id: foo

namespace: bar

kube-apply->: var "kubectl apply -f {{id}} -n {{namespace}}"
```

Should equal this 

```yaml
id: foo

namespace: bar

kube-apply: kubectl apply -f foo -n bar
```

But it equals this 
```yaml
id: foo

namespace: bar

kube-apply: bar
```
