### ISSUE TITLE
Make dict fields in hooks parsable  

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#64]
Would be super convenient to be able to make dict fields in hooks parsable (ie parsed for hooks). For instance: 

```yaml 
  render:
    for: stack_versions
    ->: generate templates/{{item}} {{cluster_env}}/{{network_name}}-{{network_version}}/{{item}}
    extra_context:
      service: "{{item}}"
```
Could have 

```yaml 
  render:
...
    extra_context:
      service->: yaml foo.yaml 
```
Or could be 

```yaml 
  render:
...
    extra_context->: yaml foo.yaml 
```
The latter I don't think is worth supporting because hooks can be called from jinja.
