### ISSUE TITLE
Fix help screen 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#92]
Right now a multi-line description looks trashed. 

```yaml
<-:
  help: A CLI thing

  stuff:
    default: things
    type: str
    description: Some things that do stuff

  things:
    type: bool
    default: true
    description: |
      Some stuff that does things and stuff and things and stuff and things and stuff 
      and things and stuff and things and stuff and things and stuff and.
# ....
```

```text
A CLI thing

flags:
    --things      Some stuff that does things and stuff and things and stuff and things and
stuff
and things and stuff and things and stuff and things and stuff and.
options:
    --stuff [str] Some things that do stuff
```

Should probably integrate some kind of form from rich.
