### ISSUE TITLE
Allow more types for `return` in declarative hook 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle-box#93]
Right now only strings are allowed as inputs to the `return` field, 

For instance:

```yaml
greeter<-:
  exec:
    target: world
    hi->: print Hello {{target}}!
  return: target
call->: greeter
```

The output would now be:

```yaml
call: world
```

Would be cool to allow:

```yaml
greeter<-:
  exec:
    foo: bar 
    target: world
    hi->: print Hello {{target}}!
  return: 
    - target
    - hi
call->: greeter
```

The output would now be:

```yaml
call: 
  target: world
  hi: null 
```

This seems to be the most natural meaning of what a list of strings for `return` would be.
